# Generated by Django 4.0.10 on 2024-02-21 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_jason', '0002_flightdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 21, 28, 9, 153670)),
            preserve_default=False,
        ),
    ]
